### ISSUE TITLE
[瞳孔震惊] UnsupportedClassVersionError

### ISSUE THREAD

**Issue by Zhongren233** [MisakaTAT/Shiro#1]
哇靠我看了一下怎么jdk 15+

可否提供jdk8的编译,虽然我个人是拥抱新版本 

但是部分依赖 确实不支持jdk8以上..

**Comment by MisakaTAT** [comment]
这个有在考虑，由于下一个 LTS 版本 JAVA 17 快发布了，本来计划是仅支持最新的 LTS 版本，但是也有很多人和我反馈过能否降低到 1.8 版本的问题，目前正在考虑多版本的字节码发行jar包。

如果着急使用的话可以临时按如下方法解决：

- `com.mikuac.shiro.handler.EventHandler` 类中的 `增强switch` 语法更改为 `普通switch`
- `pom.xml` 内的 `jdk` 版本降低至 `1.8` 重新编译

**Comment by Zhongren233** [comment]
感谢回复，已自行编译。

**Comment by MisakaTAT** [comment]
目前编译版本已降至 `Java8`，对应版本为 `v1.1.5`，请等待 Maven Repo 同步
