### ISSUE TITLE
佬没有做戳一戳时间吗？

### ISSUE THREAD

**Issue by yixihan** [MisakaTAT/Shiro#104]
![image](https://user-images.githubusercontent.com/72201112/204012127-7cf08952-32d6-45db-a610-1deb2dd4662f.png)

**Comment by MisakaTAT** [comment]
https://github.com/MisakaTAT/Shiro/blob/2fbc1286593cb47af98feccca404e132c74501cc/src/main/java/com/mikuac/shiro/dto/event/notice/PokeNoticeEvent.java#L41-L42

有的呀

**Comment by yixihan** [comment]
> 

打错字了，是事件

**Comment by yixihan** [comment]
> > 
> 
> 打错字了，是事件

我尝试用@MessageHandler注解监听戳一戳事件，似乎没有触发

**Comment by MisakaTAT** [comment]
`@MessageHandler` 注解是用来监听消息事件的，如果你想监听戳一戳的话需要继承 `BotPlugin` 然后重写 `onGroupPokeNotice` 方法，这个暂时没实现注解，因为还挺多的，就只写了一些常用的注解，你在群里嘛，可以加群问比较方便点。

**Comment by MisakaTAT** [comment]
注解未实现的事件可以继承 `BotPlugin` 然后重写对应方法去实现，文档见 https://misakatat.github.io/shiro-docs/#重写方式 文档目前还未完善，具体的可以查看 `BotPlugin` 的源码，都有注释的

**Comment by yixihan** [comment]
> 注解未实现的事件可以继承 `BotPlugin` 然后重写对应方法去实现，文档见 [https://misakatat.github.io/shiro-docs/#重写方式](https://misakatat.github.io/shiro-docs/#%E9%87%8D%E5%86%99%E6%96%B9%E5%BC%8F) 文档目前还未完善，具体的可以查看 `BotPlugin` 的源码，都有注释的

okok，目前没在群里
