### ISSUE TITLE
JSONException in push any message evnt

### ISSUE THREAD

**Issue by Zhongren233** [MisakaTAT/Shiro#134]
暂时不知道如何复现 现场只有一张截图【梅村日志】

![ADG`K%C60)U $3LT0M 74L1](https://user-images.githubusercontent.com/62706664/236690083-28f48074-0857-4358-b952-2b5571132918.png)

**Comment by MisakaTAT** [comment]
梅村日志还行，issue先开着，看看还能不能复现

**Comment by MisakaTAT** [comment]
Fixed

**Comment by MisakaTAT** [comment]
还有就是之前的群又双叒叕寄了

**Comment by Zhongren233** [comment]
好似
