### ISSUE TITLE
fastjson解析msg报错

### ISSUE THREAD

**Issue by XM2510136957** [MisakaTAT/Shiro#141]
**详细描述**
关于问题的详细描述。
fastjson解析msg报错
**预期结果**
你希望得到什么结果?
fastjson解析msg不报错
**当前结果**
实际产生的结果是什么？
fastjson解析msg报错
**在最新的RELEASE版本中能否复现？**
是否尝试过最新版本的Shiro？
是的
**复现方法**
如果可以，请提供能够稳定复现的方法。

**屏幕截图或者日志**
请添加屏幕截图或日志以快速定位问题。
![image](https://github.com/MisakaTAT/Shiro/assets/18229485/41a50bbc-112d-4a5d-b213-4f1731bbe2d0)

**运行或开发环境**

- 系统版本：[ 例如 CentOS Linux release 8.2.2004 (Core)  ]
- Shiro版本：[ 例如 v.1.2.7 ]
- 客户端版本：[ 例如 go-cqhttp v1.0.0-beta8-fix2 ]
- JDK版本：[ 例如 OpenJDK 17.0.1 2021-10-19 LTS ]
- SpringBoot版本：[ 例如 2.5.5 ]

**Comment by MisakaTAT** [comment]
#134

**Comment by MisakaTAT** [comment]
Fixed
