### ISSUE TITLE
有考虑兼容官方api吗

### ISSUE THREAD

**Issue by zhengyuelai** [MisakaTAT/Shiro#173]
**详细描述**
功能的简要说明。

**基本示例**
https://docs.qq.com/doc/DRkVHT1N2a1JYSnVr

**其它**
您还需要添加其他内容吗？

**Comment by zhzhongshi** [comment]
猜你想找: [Gensokyo](https://github.com/Hoshinonyaruko/Gensokyo)

**Comment by MisakaTAT** [comment]
既然有现成的项目话，可以试试看（

**Comment by xboyuan** [comment]
我使用 [Gensokyo](https://github.com/Hoshinonyaruko/Gensokyo) 套用本项目的demo程序，可以正常连接，也能收到事件的消息，但是为何进不去事件处理方法呢？
![image](https://github.com/MisakaTAT/Shiro/assets/40412198/6f6e8aa8-0351-4264-a1d6-8e6b17465da9)

**Comment by MisakaTAT** [comment]
> 我使用 [Gensokyo](https://github.com/Hoshinonyaruko/Gensokyo) 套用本项目的demo程序，可以正常连接，也能收到事件的消息，但是为何进不去事件处理方法呢？ ![image](https://user-images.githubusercontent.com/40412198/281949193-6f6e8aa8-0351-4264-a1d6-8e6b17465da9.png)

application.yml 配置了 PluginList 吗？

**Comment by zhengyuelai** [comment]
> 我使用 [Gensokyo](https://github.com/Hoshinonyaruko/Gensokyo) 套用本项目的demo程序，可以正常连接，也能收到事件的消息，但是为何进不去事件处理方法呢？ ![image](https://user-images.githubusercontent.com/40412198/281949193-6f6e8aa8-0351-4264-a1d6-8e6b17465da9.png)

是用[Gensokyo](https://github.com/Hoshinonyaruko/Gensokyo)作为客户端吗，[Shiro](https://github.com/MisakaTAT/Shiro)再跟Gensokyo通信？

**Comment by xboyuan** [comment]
> > 我使用 [Gensokyo](https://github.com/Hoshinonyaruko/Gensokyo) 套用本项目的demo程序，可以正常连接，也能收到事件的消息，但是为何进不去事件处理方法呢？ ![image](https://user-images.githubusercontent.com/40412198/281949193-6f6e8aa8-0351-4264-a1d6-8e6b17465da9.png)
> 
> 是用[Gensokyo](https://github.com/Hoshinonyaruko/Gensokyo)作为客户端吗，[Shiro](https://github.com/MisakaTAT/Shiro)再跟Gensokyo通信？

是的，完全是按照文档的方式配置，也试过去除此种方式使用注解的模式，依旧是进入不了处理方法

**Comment by MisakaTAT** [comment]
> > > 我使用 [Gensokyo](https://github.com/Hoshinonyaruko/Gensokyo) 套用本项目的demo程序，可以正常连接，也能收到事件的消息，但是为何进不去事件处理方法呢？ ![image](https://user-images.githubusercontent.com/40412198/281949193-6f6e8aa8-0351-4264-a1d6-8e6b17465da9.png)
> > 
> > 
> > 是用[Gensokyo](https://github.com/Hoshinonyaruko/Gensokyo)作为客户端吗，[Shiro](https://github.com/MisakaTAT/Shiro)再跟Gensokyo通信？
> 
> 是的，完全是按照文档的方式配置，也试过去除此种方式使用注解的模式，依旧是进入不了处理方法

那奇怪了，不过我现在没内测权限也没法测试，可能得等一等了
