### ISSUE TITLE
新增webscoket client支持。

### ISSUE THREAD

**Issue by chiangchingtien** [MisakaTAT/Shiro#196]
增加client端支持。

主要就是依赖配置项加载server端或者client端。
    @ConditionalOnMissingBean
    @ConditionalOnProperty(value = "bot.shiro.ws.server", havingValue = "true")
    public WebSocketServerHandler createShiroSeverWebSocketHandler() {}

    @ConditionalOnMissingBean
    @ConditionalOnProperty(value = "bot.shiro.ws.client", havingValue = "true")
    public WebSocketClientHandler createShiroClientWebSocketHandler() {}

**Comment by HyperCherry** [comment]
同样，希望增加正向WebSocket支持，便于将Onebot标准实现端部署在服务器时，让Shiro连接到远端的Onebot实现（让Shiro连接到反向WebSocket服务器）

**Comment by MisakaTAT** [comment]
最近比较忙，可能还需要再等等，如果有大佬做好了话能直接pr最好了 :D

**Comment by MisakaTAT** [comment]
> 同样，希望增加正向WebSocket支持，便于将Onebot标准实现端部署在服务器时，让Shiro连接到远端的Onebot实现（让Shiro连接到反向WebSocket服务器）

已支持，等晚点release之后可以试一下。
