### ISSUE TITLE
[BUG] AT.OFF 不会对消息去除@

### ISSUE THREAD

**Issue by xiaomujin** [MisakaTAT/Shiro#202]
**详细描述**

AT.OFF 不会对消息去除@

**预期结果**
AT.OFF 对@自己也生效

**当前结果**
不会对消息去除@

**在最新的RELEASE版本中能否复现？**
能

**复现方法**
@自己

**屏幕截图或者日志**
![image](https://github.com/MisakaTAT/Shiro/assets/38455940/cbf79c2f-9656-4242-bff0-caeb18e9627b)
![image](https://github.com/MisakaTAT/Shiro/assets/38455940/301b9f51-17a4-41a8-87e6-7fbd1f7b404a)

**Comment by MisakaTAT** [comment]
假设在cmd="hi"的情况下，那么 @bot hi 是不会生效的，OFF的默认逻辑可以理解为没设置这个参数，那么 cmd 为 hi 的情况下，发送@bot hi 是无法匹配的。
