### ISSUE TITLE
实现 CoreEvent 在online方法中bot.getLoginInfo()获取为null

### ISSUE THREAD

**Issue by Seiryuu-Qiu** [MisakaTAT/Shiro#222]
**详细描述**
实现 CoreEvent 在online方法中bot.getLoginInfo()获取为null

**屏幕截图或者日志**
![51f5833e3a95922231c30cf48f554823](https://github.com/MisakaTAT/Shiro/assets/35923395/314ad389-215e-49c7-b2bb-4bfda307aff5)

**运行或开发环境**
- Shiro版本：2.2.4

**Comment by MisakaTAT** [comment]
执行 bot.getLoginInfo() 操作的时候会导致 NIO 线程被 lock，导致无法进行后续响应处理，异步执行该动作即可。
