### ISSUE TITLE
这里是应该修复的错误

### ISSUE THREAD

**Issue by qingshu-ui** [MisakaTAT/Shiro#238]
我注意到您在这里定义了一个 xSelfId ，在首次启动时 session 中没有包含任何信息，所以它必定会经给您的 parseSelfId 方法获得 0 值
https://github.com/MisakaTAT/Shiro/blob/ffc62e7553bd91bd6b90bb9b073215d1793b27c2/src/main/java/com/mikuac/shiro/adapter/WebSocketClientHandler.java#L94

您将在这里将这个值为 0 的 xSelfId 传递给 execHandlerMsg 方法，我注意到您在 execHandlerMsg 做了相应的处理，确保不会发生空指针异常
https://github.com/MisakaTAT/Shiro/blob/ffc62e7553bd91bd6b90bb9b073215d1793b27c2/src/main/java/com/mikuac/shiro/adapter/WebSocketClientHandler.java#L114

我注意到您在这里通过 message.getPayload 获取了新的 xSelfId , 但是并没有更新到最初的 xSelfId
https://github.com/MisakaTAT/Shiro/blob/ffc62e7553bd91bd6b90bb9b073215d1793b27c2/src/main/java/com/mikuac/shiro/adapter/WebSocketClientHandler.java#L98

我通过 debug 得知首次连接时收到的上报为 lifecycle 这是一个 sub_type 为 connect 的生命周期事件，如果继续将 xSelfId 为 0 的值传递给 execHandlerMsg 会导致 无法获取到 bot 对象，将会损失这一次事件上报，我们将无法监听 connect 事件
https://github.com/MisakaTAT/Shiro/blob/ffc62e7553bd91bd6b90bb9b073215d1793b27c2/src/main/java/com/mikuac/shiro/task/ShiroAsyncTask.java#L37

**Comment by MisakaTAT** [comment]
感谢反馈，已修复。
