### ISSUE TITLE
添加@MessageHandler注解和sendMessage方法

### ISSUE THREAD

**Issue by kzw200015** [MisakaTAT/Shiro#24]
**功能描述**
添加`@MessageHandler`注解和`sendMessage`方法
`@MessageHandler`同时监听PrivateMessage和GroupMessage，`sendMessage`方法根据Message类型和来源发送消息。比如是PrivateMessage就`sendPrivateMessage`到Event的userId

**Comment by MisakaTAT** [comment]
之前有考虑过，后面太忙就鸽了，可以考虑添加，我这两天写一下，感谢建议。

**Comment by MisakaTAT** [comment]
已实现，版本为 v1.1.8，目前 Release 到 Maven 仓库了，需要过几个小时等待同步。

**Comment by kzw200015** [comment]
新的`sendMsg`方法感觉有点不合理，targetId仍然需要调用方判断消息类型，传入相应的userId或者groupId。这样的话方法内的消息类型判断就没什么意义了，实际使用起来和之前相比并没有更加方便
类似这样的实现会不会更好
```
fun WholeMessageEvent.sendMsg(bot: Bot, msg: String, autoEscape: Boolean): ActionData<MsgId>? {
    return when (this.messageType) {
        "group" -> bot.sendGroupMsg(this.groupId, msg, autoEscape)
        "private" -> bot.sendPrivateMsg(this.userId, msg, autoEscape)
        else -> null
    }
}
```

**Comment by MisakaTAT** [comment]
感谢指正，目前改了一版，你觉得如何？
```kotlin
@MessageHandler
fun test(bot: Bot, event: WholeMessageEvent) {
    bot.sendMsg(event, "hello", false)
}
```
https://github.com/MisakaTAT/Shiro/blob/3206cb5599f5be6360a00e04abe89c6fd0ee7f1e/src/main/java/com/mikuac/shiro/core/Bot.java#L64-L83

**Comment by kzw200015** [comment]
挺好的，这样就更加方便了

**Comment by MisakaTAT** [comment]
今天晚上会再发一版，v1.1.9
