### ISSUE TITLE
This may be a spelling error

### ISSUE THREAD

**Issue by qingshu-ui** [MisakaTAT/Shiro#241]
It may be `getRawType()` and `setRawType()`
https://github.com/MisakaTAT/Shiro/blob/521a268d3c2373a48b567ea05ef0109baf0a12e3/src/main/java/com/mikuac/shiro/model/ArrayMsg.java#L34
https://github.com/MisakaTAT/Shiro/blob/521a268d3c2373a48b567ea05ef0109baf0a12e3/src/main/java/com/mikuac/shiro/model/ArrayMsg.java#L38

**Comment by MisakaTAT** [comment]
thanks.
