### ISSUE TITLE
调用deleteFriend接口删除好友时出错

### ISSUE THREAD

**Issue by MinMinGuGu** [MisakaTAT/Shiro#252]
**详细描述**
```java
@PrivateMessageHandler
@MessageHandlerFilter(cmd = "删除好友")
 public void deleteFriends(Bot bot, PrivateMessageEvent event, Matcher matcher) {
    ActionList<FriendInfoResp> friendList = bot.getFriendList();
    for (FriendInfoResp friendInfoResp : friendList.getData()) {
            Long userId = friendInfoResp.getUserId();
            // 实际上并不是删除全部好友  而是在这段循环中加了条件过滤 这里省略没写
            bot.deleteFriend(userId);
    }
}
```
上面的代码执行时，在控制台打印了如下错误：
`Action failed: Key: , Message: must have required property 'friend_id'`

**预期结果**
成功删除指定QQ号的好友。

**当前结果**
报错，删除无效。

**在最新的RELEASE版本中能否复现？**
```xml
        <dependency>
            <groupId>com.mikuac</groupId>
            <artifactId>shiro</artifactId>
            <version>2.3.3</version>
        </dependency>
```
2.3.3版本出现。

**复现方法**
直接调用`deleteFriend`接口并传入已有好友QQ号。

**屏幕截图或者日志**
暂无。

**运行或开发环境**

- 系统版本：[ Red Hat Enterprise Linux 9.4 (Plow)  ]
- Shiro版本：[ v.2.3.3 ]
- 客户端版本：[ mlikiowa/napcat-docker:latest ]
- JDK版本：[ eclipse-temurin:17.0.13_11-jre-ubi9-minimal ]
- SpringBoot版本：[ 3.3.5 ]

**Comment by MisakaTAT** [comment]
因为原先gocqhttp接收的是user_id或者id，napcat是friend_id。懒得一个个适配了。直接customRequest构造一个吧。

```java
Map<String, Object> params = new HashMap<>();
params.put("friend_id", "1234567");
bot.customRequest(() -> "delete_friend", params);
```

**Comment by MinMinGuGu** [comment]
好，我再看下，这个issues可能要提给napcat了。

**Comment by MinMinGuGu** [comment]
更新，napcat在3.6.1版本已经规范化实现好友删除接口。
