### ISSUE TITLE
獲取精華消息 (getEssenceMsgList) 的 message_id 是 string, 但 獲取消息 (getMsg) 時需要填入參數的 message_id 是 int

### ISSUE THREAD

**Issue by eric2788** [MisakaTAT/Shiro#28]
**功能描述**

建議返回 int 方便後續不用 parse 成 int?

這個也不算bug...算是改進建議

**Comment by eric2788** [comment]
![image](https://user-images.githubusercontent.com/6276840/146053963-f47a4bc3-dba5-4566-9619-c0eca25219d6.png)

**Comment by eric2788** [comment]
go-cqhttp 也是 int32 
![image](https://user-images.githubusercontent.com/6276840/146054195-b59adf2d-7286-4891-b303-483a277b405f.png)

**Comment by MisakaTAT** [comment]
已修正

**Comment by eric2788** [comment]
好的
