### ISSUE TITLE
痛失你群

### ISSUE THREAD

**Issue by Zhongren233** [MisakaTAT/Shiro#34]
**功能描述**
![image](https://user-images.githubusercontent.com/62706664/149606420-4ded9140-e4b4-4051-9d3f-4545bb8be1e3.png)

**Comment by MisakaTAT** [comment]
梅开二度了属于是，之前键政封了一次，我天天在群里说别键政，要聊去tg，r18图私聊搜，就是没人听（，晚点重新开个群吧

**Comment by MisakaTAT** [comment]
738431739

**Comment by MisakaTAT** [comment]
谢邀，又没了，860346522
