### ISSUE TITLE
[問題] FriendAddRequestEvent 沒有繼承 RequestEvent 故無法獲取 flag 值

### ISSUE THREAD

**Issue by eric2788** [MisakaTAT/Shiro#4]
如題.... 
還是有別的方法可以獲取 flag 來接受好友請求？

**Comment by MisakaTAT** [comment]
感谢反馈，该问题是由于 `FriendAddRequestEvent` 错误继承至 `Event` 导致无法获取 `RequestEvent` 值，当前问题已在最新版本中修复，对应版本为 `v1.1.3`，请等待 `Maven Repo` 同步。

**Comment by eric2788** [comment]
v1.1.3 已經解決了，謝謝
