### ISSUE TITLE
插件异常后在控制台无输出

### ISSUE THREAD

**Issue by coder-tq** [MisakaTAT/Shiro#41]
**详细描述**
插件出现异常后，未将异常信息输出至标准输出

**预期结果**
将异常栈信息输出至标准输出

**当前结果**
无异常信息

**在最新的RELEASE版本中能否复现？**
是

**复现方法**
throw new RuntimeException("Test");

**屏幕截图或者日志**
无报错日志

**运行或开发环境**
- 系统版本：[  CentOS 7  ]
- Shiro版本：[  v.1.2.7 ]
- 客户端版本：[  go-cqhttp v1.0.0-rc1 ]
- JDK版本：[  openjdk version "1.8.0_282" ]
- SpringBoot版本：[ v2.2.6.RELEASE ]

**Comment by MisakaTAT** [comment]
已修复，这个 issues 我就先关了，有问题的话你再重新打开吧。
