### ISSUE TITLE
群寄了

### ISSUE THREAD

**Issue by yuyuko233** [MisakaTAT/Shiro#71]
如题, 群没了

**Comment by MisakaTAT** [comment]
> 如题, 群没了

860346522

**Comment by yuyuko233** [comment]
> > 如题, 群没了
> 
> [860346522](tel:860346522)

搜不到

**Comment by MisakaTAT** [comment]
> > > 如题, 群没了
> 
> > 
> 
> > [860346522](tel:860346522)
> 
> 
> 
> 搜不到

可以了
