### ISSUE TITLE
能否加个正向WS

### ISSUE THREAD

**Issue by lvyunqi** [MisakaTAT/Shiro#81]
**详细描述**
大佬能否加上正向ws

**Comment by MisakaTAT** [comment]
可以考虑加上，不过一般来说有反向ws就够用了，可以简单描述下是什么场景需要用到正向ws吗？

**Comment by MisakaTAT** [comment]
最近比较忙，正反向ws用起来是没有区别的，所以我想先了解下是什么使用场景再考虑做不做，暂时没收到反馈，这个issues我先关了，有需要你再打开吧
